apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
        - env:
            - name: IS_MONGO_CLOUD_PROVIDED
              valueFrom:
                configMapKeyRef:
                  key: IS_MONGO_CLOUD_PROVIDED
                  name: env-mongo-env
            - name: MONGODB_DEVELOPMENT_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_DEVELOPMENT_DATABASE_NAME
                  name: env-mongo-env
            - name: MONGODB_DEVELOPMENT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_DEVELOPMENT_PASSWORD
                  name: env-mongo-env
            - name: MONGODB_DEVELOPMENT_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_DEVELOPMENT_URL
                  name: env-mongo-env
            - name: MONGODB_DEVELOPMENT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_DEVELOPMENT_USERNAME
                  name: env-mongo-env
            - name: MONGODB_PROD_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_PROD_DATABASE_NAME
                  name: env-mongo-env
            - name: MONGODB_PROD_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_PROD_PASSWORD
                  name: env-mongo-env
            - name: MONGODB_PROD_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_PROD_URL
                  name: env-mongo-env
            - name: MONGODB_PROD_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_PROD_USERNAME
                  name: env-mongo-env
            - name: MONGODB_TEST_DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_TEST_DATABASE_NAME
                  name: env-mongo-env
            - name: MONGODB_TEST_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_TEST_PASSWORD
                  name: env-mongo-env
            - name: MONGODB_TEST_URL
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_TEST_URL
                  name: env-mongo-env
            - name: MONGODB_TEST_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGODB_TEST_USERNAME
                  name: env-mongo-env
          image: mongo
          name: mongodb
          resources: {}
      restartPolicy: Always
status: {}
